# Generated by Django 5.2.5 on 2025-11-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo que aparecerá en la parte superior de los documentos impresos.', null=True, upload_to='configuracion/')),
                ('pie_de_pagina', models.TextField(blank=True, help_text='Texto que aparecerá en el pie de página de los documentos impresos.')),
                ('mostrar_seccion_garante', models.BooleanField(default=True, help_text='Si está marcado, se mostrará la información del garante en el reporte.')),
                ('mostrar_tabla_amortizacion', models.BooleanField(default=True, help_text='Si está marcado, se mostrará la tabla de amortización completa.')),
            ],
            options={
                'verbose_name': 'Configuración de Impresión',
                'verbose_name_plural': 'Configuración de Impresión',
            },
        ),
    ]
