# Generated by Django 5.2.5 on 2025-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresion',
            name='email_empresa',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto de la empresa.', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='nombre_empresa',
            field=models.CharField(default='Nombre de tu Empresa', help_text='El nombre de la empresa que aparecerá en los documentos.', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionimpresion',
            name='telefono_empresa',
            field=models.CharField(blank=True, help_text='Teléfono de contacto de la empresa.', max_length=50),
        ),
    ]
